### ISSUE TITLE
tools for conventional commits

### ISSUE THREAD

**Issue by jjangga0214** [devilune/tonbly#4]
If you want contributors to follow conventional commits, I'd like to recommend some handy tools.

1. [conventional-changelog/commitlint](https://github.com/conventional-changelog/commitlint): This is literally linter for conventional commits. It seems you want to use angular preset, and commitlint allows using both preset and fine tuning as well. 
2. [husky](https://github.com/typicode/husky): You can register git hook. For example, this snippet will run commitlint to every commit, and prevent invalid message to be committed. You can skip husky when needed by passing `HUSKY_SKIP_HOOKS=1` as env var.
```bash
{
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
```
3. [commitizen/cz-cli](https://github.com/commitizen/cz-cli): This is a handy interactive tool. You can register it to package.json, like `yarn commit` or `npm run commit`. Or, you can use it with git hook, to force using it when making commit.

**Comment by convcha** [comment]
@jjangga0214 Sorry for late reply.
Thank you for recommendation!
I will introduce those tools and close this issue when my PR merged.

**Comment by convcha** [comment]
@jjangga0214 I have introduced commitlint and husky.
These tools are really useful!
Thank you very much.
